config/routes.rb
PetThing::Application.routes.draw do

  
  
  resources :emergencias
  resources :procedimientos_medicos_y_de_enfermeria
  get 'dashboard1/mapa',  to: 'dashboard1#mapa', as: "mapa"

  get 'dashboard1/graficas',  to: 'dashboard1#graficas', as: "graficas"

  get 'informes/index',  to: 'informes#index', as: "info_link"

  get 'informes/mensual_actividades_medicas',    to: 'informes#mensual_actividades_medicas', as: "mensual_actividades_medicas"

  get 'informes/aerocivil',    to: 'informes#aerocivil', as: "aerocivil"

  get 'informes/procedimientos_medicos_enfermeria',    to: 'informes#procedimientos_medicos_enfermeria', as: "procedimientos_medicos_enfermeria"

  get 'informes/pacientes_atendidos_por_empresas',  to: 'informes#pacientes_atendidos_por_empresas', as: "pacientes_atendidos_por_empresas"

  get 'informes/usuarios',  to: 'informes#usuarios', as: "usuarios"

  get 'informes/doctores',  to: 'informes#doctores', as: "doctores"

  get 'informes/historia_usuario',  to: 'informes#historia_usuario', as: "historia_usuario"

  get "reportes", :to => "pages#reportes"

  
  get "get_pacientes/:cedula", to: "pacientes#get_pacientes", as: "get_pacientes"

  resources :paises
  resources :cie10s , :defaults => { :format => :json }

  resources :empresas, :path => "empresas"
  resources :procedimientos, :path => "procedimientos"
  resources :diagnosticos,  :path => "diagnosticos"
  resources :roles, :path => "roles"
  resources :aeropuertos, :path => "aeropuertos"

  resources :ciudades, :path => "ciudades" do
    collection do
      get :autocomplete_ciudad_nombre
    end
  end

  resources :arles, :path => "arl" do
    collection do
      get :autocomplete_arl_nombre
    end
  end

  resources :epses, :path => "eps" do
    collection do
      get :autocomplete_eps_nombre
    end
  end

  resources :users, :path => "usuarios"
  resources :roles, :path => "roles"

  resources :sheets
  resources :material_sheets

  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'

  get 'users/historias/:id/:estado', to: "users#historias", as: "users_historias"

  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  get "logout" => "sessions#destroy", :as => "logout"

   

  resources :pacientes, :path => "pacientes",  only: [:new, :create, :index, :destroy, :show, :edit, :update]  do
    
    resources :historias_clinicas,  :path => "historias_clinicas", only: [:new, :create, :index, :destroy, :show, :edit, :update] do
      resources :historia_fisicas  ,  :path => "historia_fisicas", only: [:new, :create, :index, :destroy, :show, :edit, :update]
      resources :steps,  :path => "steps", only: [:show, :update, :edit], controller: 'historia_clinica/steps'
      resources :notas_progreso,  :path => "notas_progreso", only: [:new, :create, :index, :destroy, :show, :edit, :update]
    end
  end

  root to: 'pages#home'

 

end
   

app/models/paciente.rb
# == Schema Information
#
# Table name: pacientes
#
#  id               :integer          not null, primary key
#  ciudad           :string
#  primer_nombre    :string
#  segundo_nombre   :string
#  primer_apellido  :string
#  segundo_apellido :string
#  nombre_completo  :text
#  email            :string
#  tipo_documento   :string
#  documento        :string
#  fecha_nacimiento :date
#  genero           :string
#  profesion        :string
#  tipo_sangre      :string
#  nacionalidad     :string
#  direccion        :string
#  condicion        :string
#  user_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  pais_codigo      :string
#

class Paciente < ActiveRecord::Base
  belongs_to :eps
  belongs_to :arl
  # belongs_to :ciudad
  belongs_to :user
  has_many :historias_clinicas
   has_many :progress_notes
 has_many :historia_fisicas, dependent: :destroy
  # accepts_nested_attributes_for :ciudad, :reject_if => lambda {|a| a[:nombre].blank?}

  validates :primer_nombre, :presence => { :message => " es un Campo Obligatorio"}
  validates :primer_apellido, :presence => { :message => " es un Campo Obligatorio"}
  validates :tipo_documento, :presence => { :message => " es un Campo Obligatorio"}
  validates :documento, :presence => { :message => " es un Campo Obligatorio"}
  validates :genero, :presence => { :message => " es un Campo Obligatorio"}
  validates :fecha_nacimiento, :presence => { :message => " es un Campo Obligatorio"}
  validates :tipo_sangre, :presence => { :message => " es un Campo Obligatorio"}
  validates :profesion, :presence => { :message => " es un Campo Obligatorio"}
  validates :direccion, :presence => { :message => " es un Campo Obligatorio"}
  validates :nacionalidad, :presence => { :message => " es un Campo Obligatorio"}
  validates :documento, :uniqueness =>  { message: "  Ya Fue registrado" }
  validates :email, :uniqueness =>  { message: " Ya Fue registrado" }, :if => :condition_testing?

  def condition_testing?
    !(email == "N/A")
  end




  def self.search(search)
    where("(primer_nombre || ' ' || segundo_nombre || ' ' || primer_apellido  || ' ' || segundo_apellido) like '%#{search}%'  or 
      segundo_nombre like '%#{search}%' or 
      segundo_apellido like '%#{search}%' or 
      email like '%#{search}%' or 
      documento like '%#{search}%' or direccion like
    '%#{search}%'").order(:id)
  end

end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]
  # before_filter :find_paciente_clinic_histories

  def index
    @pacientes = Paciente.search(params[:search]).page(params[:page]).per_page(20)
  end

  def show
  end

  def new
    @paciente = Paciente.new
   # @paciente.build_ciudad
  end

  def edit

  end

  def create
    @paciente = Paciente.new(paciente_params)
    if @paciente.email.blank?
      @paciente.email = "N/A"
    end
    respond_to do |format|
      if @paciente.save
        format.html { redirect_to new_paciente_historia_clinica_path(@paciente), notice: 'Paciente creado Satisfactoriamente.' }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end


  def get_pacientes

    render :text => Paciente.where(documento: params[:cedula]).count

  end  

  def update

    respond_to do |format|
      if @paciente.update(paciente_params)

        format.html { redirect_to @paciente, notice: 'Paciente actualizado Satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @paciente.destroy
    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: 'Paciente eliminado Satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

    private
    def set_paciente
      @paciente = Paciente.find(params[:id])

    end

    def paciente_params
      params.require(:paciente).permit!
    end


end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_display.html.erb
<div class="container-fluid" style="margin: 25px; margin-top: -20px;">
  <div class="row">
    <div class="col-lg-12">

      <span  class="btn btn-link btn-xs  pull-left pagination pagination">
        <h1 class="title">Pacientes</h1>
      </span>

      <% if current_user.rol_id != 3 %>
      <span  class="btn btn-link btn-xs pull-right" style="margin-top: 20px !important;">
        <%= link_to 'Nuevo Paciente', new_paciente_path, :class =>"btn btn-info color_blanco" %>  
      </span>
      <% end %>

      <div class="row" >
        <div class="col-lg-12" style="margin-top: -40px;">
          <%= will_paginate @roles, renderer: BootstrapPagination::Rails, :previous_label =>'Atras', :next_label => 'Siguiente' %>
        </div>
      </div>

      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th colspan="5">
              <%= form_tag request.path, :method => 'get', :class => '' do %>
                <div class="row">
                  <div class="col-lg-8">
                    <div class="input-group custom-search-form">
                      <%= text_field_tag :search, params[:search], :placeholder =>
                      "Busca por el Nombre", :class => 'form-control' %>
                      <span class="input-group-btn">

                        <%= button_tag(type: "submit", class: "btn principal") do %>
                          <span class="glyphicon glyphicon-search"></span>
                        <% end %>
                      </span>
                    </div>
                  </div>
                  <div class="col-lg-4">
                    <a class="btn icon-btn btn-primary" href="#">
                      <span class="glyphicon btn-glyphicon glyphicon glyphicon-user img-circle text-primary"></span>
                      Numero de Pacientes registrados
                      <%= Paciente.count %>
                    </a>
                  </div>
                </div>
              <% end %>
            </th>
          </tr>
          <tr class ="x1" >
            <th width="5% !important;">Id</th>
            <th width="30% !important;">Nombres y Apellidos</th>
            <th width="15% !important;">Documento</th>
           
            <th width="20% !important;">Opciones</th>
          </tr>
        </thead>
        <tbody>
          <% @pacientes.each do |paciente| %>
            <tr class ="x">
              <td><%= paciente.id %></td>
              <td>
                <%= paciente.primer_nombre.capitalize %>
                <%= paciente.segundo_nombre.capitalize %>
                <%= paciente.primer_apellido.capitalize %>
                <%= paciente.segundo_apellido.capitalize %>
              </td>
              <td><%= paciente.documento %></td>
             
              <td>

                <style type="text/css" media="screen">
                  .icono {
                    font-size: 16px;
                    color: #848484;
                  }
                  .ver_notas{
                  color: #666;
                  }
                </style>

                <%= link_to paciente, class: "btn btn-link btn-xs", title: "Ver Paciente" do %> <i class="glyphicon glyphicon-eye-open icono"></i>
                <% end %>

                <% if current_user.rol_id != 3 %>

                  <%= link_to edit_paciente_path(paciente), class: "btn btn-link btn-xs", title: "Editar Paciente" do %> <i class="glyphicon glyphicon-pencil icono"></i>
                  <% end %>

                <% end %>

                <%= link_to 'Ver Historias Clinicas(' + paciente.historias_clinicas.count.to_s + ')' , paciente_historias_clinicas_path(paciente), :class =>'btn btn-link btn-xs ver_notas' %>

              </td>

            </tr>
          <% end %>
        </tbody>  
      </table>

    </div>
  </div>
</div>

<style>

  .x td{
    padding: 5px 10px !important;
    background-color: #FBFBFB;
    color: #828282;
  }

  .x1 th{
    color: #67B0C7!important;
    background: #EFEFEF;
    font-size: 15px;      
  }

</style>

<style type="text/css" media="screen">
  .btn-glyphicon { padding:8px; background:#ffffff; margin-right:4px; }
  .icon-btn { padding: 1px 15px 3px 2px; border-radius:50px;}
</style>

app/views/pacientes/edit.html.erb
<%= render 'form' %>

app/views/pacientes/index.html.erb
<br/>
<br/>

<div class="row">
	<%= render partial: "display" %>
</div>

app/views/pacientes/new.html.erb
<%= render 'form' %>

app/views/pacientes/show.html.erb
<div class="container-fluid">
  <div id="loginbox" style = "margin-top: 30px;" class="mainbox col-md-12 col-sm-12">
    <style type="text/css">
            @import url(https://fonts.googleapis.com/css?family=Roboto);
            @import url(https://fonts.googleapis.com/css?family=Montserrat);
            .panel-heading {
                background-image: none;
                background-color: #ECECEC;
                color: #5bc0de;
                font-family: 'Roboto', sans-serif;
            }

            .panel-title{
                font-size: 30px;   
            }
            .pie_form{
                background-image: none;
                background-color: #ECECEC;
                color: white;   
            }
            .line1
            {
                display: inline-block;
                width: 30% !important;
            }

        </style>

    <div class="container-fluid navbar navbar-default" style = "margin-bottom:0px!importan">
      <div class="row">
        <br/>
        <div class="container-fluid" >
          <div class="col-sm-6">
            <%= link_to "Regresar", pacientes_path, :class=>"btn btn-info color_blanco mrg" %></div>
        </div>

        <div class="col-sm-6"></div>

      </div>
      <div>

        <br/>

        <div class="row">
          <div class="profile">
            <div class="col-sm-12">
              <div class="container-fluid">
                <div class="row col-md-12  custyle">
                  <h1 style=" font-size:25px; text-align: left;color: #22BDC8; margin-top: 0px;">
                    <span style = "margin-right:10px;color: #22BDC8; "class="glyphicon glyphicon-list-alt"></span>
                    Datos Paciente
                  </h1>

                  <table class="table table-striped custab table-bordered table-hover">

                    <tr>
                      <th>Nombres:</th>
                      <td>
                        <%= @paciente.primer_nombre %>
                        <%= @paciente.segundo_nombre %></td>
                      <th>Apellidos:</th>
                      <td>
                        <%= @paciente.primer_apellido %>
                        <%= @paciente.segundo_apellido %></td>
                    </tr>
                    <tr>
                      <th>Email:</th>
                      <td>
                        <%= @paciente.email %></td>
                      <th>Tipo Documento:</th>
                      <td>
                        <%= @paciente.tipo_documento %></td>
                    </tr>
                    <tr>
                      <th>Documento:</th>
                      <td>
                        <%= @paciente.documento %></td>
                      <th>Fecha Nacimiento:</th>
                      <td>
                        <%= @paciente.fecha_nacimiento %></td>
                    </tr>

                    <tr>
                      <th>Genero:</th>
                      <td>
                        <%= @paciente.genero %></td>
                      <th>Profesión:</th>
                      <td>
                        <%= @paciente.profesion %></td>
                    </tr>

                    <tr>
                      <th>Tipo Sanguineo:</th>
                      <td>
                        <%= @paciente.tipo_sangre %></td>
                      <th>Nacionalidad:</th>
                      <td>
                        <%= @paciente.nacionalidad %></td>
                    </tr>

                    <tr>
                      <th>Dirección:</th>
                      <td>
                        <%= @paciente.direccion %></td>
                    </tr>

                  </table>
                </div>
              </div>
            </div>
            <div class="col-xs-12 text-center">
              <div class="col-xs-12 col-sm-4 emphasis">

                <% if current_user.rol_id != 3 %>

                <%= link_to ' Nueva Historia Clinica',  new_paciente_historia_clinica_path(@paciente), :class =>
                'btn btn-primary  color_blanco principal'  %>
                <% end %></div>
              <div class="col-xs-12 col-sm-4 emphasis">
                <% if @paciente.historias_clinicas.count != 0 
                        @alejo = @paciente.historias_clinicas.last
                          %>

                <%= link_to ' Nueva Nota de Evolucion', new_paciente_historia_clinica_nota_progreso_path(@paciente, @alejo.id), :class =>
                'btn btn-primary  color_blanco principal' %>
                <% end %></div>
              <div class="col-xs-12 col-sm-4 emphasis">
                <%= link_to 'Ver Historias Clinicas ', paciente_historias_clinicas_path(@paciente), :class =>'btn btn-primary color_blanco principal' %></div>
            </div>
          </div>

          <br/>
          <br/>
          <br/>
        </div>
      </div>
    </div>
    <style type="text/css">
    @import url(http://fonts.googleapis.com/css?family=Lato:400,700);
    
body {
    font-family: 'Lato', 'sans-serif';
}

.profile {
    min-height: 290px;
    display: inline-block;
}

figcaption.ratings {
    margin-top:20px;
}

figcaption.ratings a {
    color:#f1c40f;
    font-size:11px;
}

figcaption.ratings a:hover {
    color:#f39c12;
    text-decoration:none;
}

.divider {
    border-top:1px solid rgba(0,0,0,0.1);
}

.emphasis {
    border-top: 4px solid transparent;
}


.emphasis h2 {
    margin-bottom:0;
}

span.tags {
    background: #1abc9c;
    border-radius: 2px;
    color: #f5f5f5;
    font-weight: bold;
    padding: 2px 4px;
}

.dropdown-menu {
    background-color: #34495e;    
    box-shadow: none;
    -webkit-box-shadow: none;
    width: 250px;
    margin-left: -125px;
    left: 50%;
}

.dropdown-menu .divider {
    background:none;    
}

.dropdown-menu>li>a {
    color:#f5f5f5;
}
    
.dropup .dropdown-menu {
    margin-bottom:10px;
}
    
.dropup .dropdown-menu:before {
    content: "";
    border-top: 10px solid #34495e;
    border-right: 10px solid transparent;
    border-left: 10px solid transparent;
    position: absolute;
    bottom: -10px;
    left: 50%;
    margin-left: -10px;
    z-index: 10;
}
</style>