config/routes.rb
PetThing::Application.routes.draw do

  
  
  resources :emergencias
  resources :procedimientos_medicos_y_de_enfermeria
  get 'dashboard1/mapa',  to: 'dashboard1#mapa', as: "mapa"

  get 'dashboard1/graficas',  to: 'dashboard1#graficas', as: "graficas"

  get 'informes/index',  to: 'informes#index', as: "info_link"

  get 'informes/mensual_actividades_medicas',    to: 'informes#mensual_actividades_medicas', as: "mensual_actividades_medicas"

  get 'informes/aerocivil',    to: 'informes#aerocivil', as: "aerocivil"

  get 'informes/procedimientos_medicos_enfermeria',    to: 'informes#procedimientos_medicos_enfermeria', as: "procedimientos_medicos_enfermeria"

  get 'informes/pacientes_atendidos_por_empresas',  to: 'informes#pacientes_atendidos_por_empresas', as: "pacientes_atendidos_por_empresas"

  get 'informes/usuarios',  to: 'informes#usuarios', as: "usuarios"

  get 'informes/doctores',  to: 'informes#doctores', as: "doctores"

  get 'informes/historia_usuario',  to: 'informes#historia_usuario', as: "historia_usuario"

  get "reportes", :to => "pages#reportes"

  
  get "get_pacientes/:cedula", to: "pacientes#get_pacientes", as: "get_pacientes"

  resources :paises
  resources :cie10s , :defaults => { :format => :json }

  resources :empresas, :path => "empresas"
  resources :procedimientos, :path => "procedimientos"
  resources :diagnosticos,  :path => "diagnosticos"
  resources :roles, :path => "roles"
  resources :aeropuertos, :path => "aeropuertos"

  resources :ciudades, :path => "ciudades" do
    collection do
      get :autocomplete_ciudad_nombre
    end
  end

  resources :arles, :path => "arl" do
    collection do
      get :autocomplete_arl_nombre
    end
  end

  resources :epses, :path => "eps" do
    collection do
      get :autocomplete_eps_nombre
    end
  end

  resources :users, :path => "usuarios"
  resources :roles, :path => "roles"

  resources :sheets
  resources :material_sheets

  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'

  get 'users/historias/:id/:estado', to: "users#historias", as: "users_historias"

  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  get "logout" => "sessions#destroy", :as => "logout"

   

  resources :pacientes, :path => "pacientes",  only: [:new, :create, :index, :destroy, :show, :edit, :update]  do
    
    resources :historias_clinicas,  :path => "historias_clinicas", only: [:new, :create, :index, :destroy, :show, :edit, :update] do
      resources :historia_fisicas  ,  :path => "historia_fisicas", only: [:new, :create, :index, :destroy, :show, :edit, :update]
      resources :steps,  :path => "steps", only: [:show, :update, :edit], controller: 'historia_clinica/steps'
      resources :notas_progreso,  :path => "notas_progreso", only: [:new, :create, :index, :destroy, :show, :edit, :update]
    end
  end

  root to: 'pages#home'

 

end
   

app/models/sheet.rb
# == Schema Information
#
# Table name: sheets
#
#  id          :integer          not null, primary key
#  nombre      :string
#  descripcion :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sheet < ActiveRecord::Base
	has_many :diagnosticos

	accepts_nested_attributes_for :diagnosticos, reject_if: :all_blank, allow_destroy: true
end

app/helpers/sheets_helper.rb
module SheetsHelper
end

app/views/sheets/_diagnostico_fields.html.erb
<div class="nested-fields well">

	<div class="field">
		<%= f.label :simbolo %>
		<br>
		<%= f.text_field :simbolo %>
	</div>
	<%= link_to_remove_association 'Eliminar', f %>
</div>

app/views/sheets/_form.html.erb
<%= form_for(@sheet) do |f| %>
<% if @sheet.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@sheet.errors.count, "error") %>prohibited this sheet from being saved:</h2>

  <ul>
    <% @sheet.errors.full_messages.each do |message| %>
    <li>
      <%= message %></li>
    <% end %></ul>
</div>
<% end %>

<div class="field">
  <%= f.label :nombre %>
  <br>
  <%= f.text_field :nombre %></div>
<div class="field">
  <%= f.label :descripcion %>
  <br>
  <%= f.text_area :descripcion %></div>
<h1 class="center">Muestra</h1>

<div class="fielset">
  <%= f.fields_for :diagnosticos do |diagnosticos| %>
  <%= render "diagnostico_fields", f: diagnosticos %>
  <% end %>
  <%= link_to_add_association 'Agregar', f, :diagnosticos, {data: {'association-insertion-method' =>'after'}} %></div>

<div class="actions">
  <%= f.submit %></div>
<% end %>

app/views/sheets/edit.html.erb
<h1>Editing Sheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sheet %>
|
<%= link_to 'Back', sheets_path %>

app/views/sheets/index.html.erb
<p id="notice">
  <%= notice %></p>

<h1>Listing Sheets</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sheets.each do |sheet| %>
    <tr>
      <td>
        <%= sheet.nombre %></td>
      <td>
        <%= sheet.descripcion %></td>
      <td>
        <%= link_to 'Show', sheet %></td>
      <td>
        <%= link_to 'Edit', edit_sheet_path(sheet) %></td>
      <td>
        <%= link_to 'Destroy', sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %></tbody>
</table>

<br>

<%= link_to 'New Sheet', new_sheet_path %>

app/views/sheets/new.html.erb
<h1>New Sheet</h1>

<%= render 'form' %>

<%= link_to 'Back', sheets_path %>

app/views/sheets/show.html.erb
<%= link_to 'Edit', edit_sheet_path(@sheet) %>
|
<%= link_to 'Back', sheets_path %>