config/routes.rb
PetThing::Application.routes.draw do

  
  
  resources :emergencias
  resources :procedimientos_medicos_y_de_enfermeria
  get 'dashboard1/mapa',  to: 'dashboard1#mapa', as: "mapa"

  get 'dashboard1/graficas',  to: 'dashboard1#graficas', as: "graficas"

  get 'informes/index',  to: 'informes#index', as: "info_link"

  get 'informes/mensual_actividades_medicas',    to: 'informes#mensual_actividades_medicas', as: "mensual_actividades_medicas"

  get 'informes/aerocivil',    to: 'informes#aerocivil', as: "aerocivil"

  get 'informes/procedimientos_medicos_enfermeria',    to: 'informes#procedimientos_medicos_enfermeria', as: "procedimientos_medicos_enfermeria"

  get 'informes/pacientes_atendidos_por_empresas',  to: 'informes#pacientes_atendidos_por_empresas', as: "pacientes_atendidos_por_empresas"

  get 'informes/usuarios',  to: 'informes#usuarios', as: "usuarios"

  get 'informes/doctores',  to: 'informes#doctores', as: "doctores"

  get 'informes/historia_usuario',  to: 'informes#historia_usuario', as: "historia_usuario"

  get "reportes", :to => "pages#reportes"

  
  get "get_pacientes/:cedula", to: "pacientes#get_pacientes", as: "get_pacientes"

  resources :paises
  resources :cie10s , :defaults => { :format => :json }

  resources :empresas, :path => "empresas"
  resources :procedimientos, :path => "procedimientos"
  resources :diagnosticos,  :path => "diagnosticos"
  resources :roles, :path => "roles"
  resources :aeropuertos, :path => "aeropuertos"

  resources :ciudades, :path => "ciudades" do
    collection do
      get :autocomplete_ciudad_nombre
    end
  end

  resources :arles, :path => "arl" do
    collection do
      get :autocomplete_arl_nombre
    end
  end

  resources :epses, :path => "eps" do
    collection do
      get :autocomplete_eps_nombre
    end
  end

  resources :users, :path => "usuarios"
  resources :roles, :path => "roles"

  resources :sheets
  resources :material_sheets

  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'

  get 'users/historias/:id/:estado', to: "users#historias", as: "users_historias"

  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  get "logout" => "sessions#destroy", :as => "logout"

   

  resources :pacientes, :path => "pacientes",  only: [:new, :create, :index, :destroy, :show, :edit, :update]  do
    
    resources :historias_clinicas,  :path => "historias_clinicas", only: [:new, :create, :index, :destroy, :show, :edit, :update] do
      resources :historia_fisicas  ,  :path => "historia_fisicas", only: [:new, :create, :index, :destroy, :show, :edit, :update]
      resources :steps,  :path => "steps", only: [:show, :update, :edit], controller: 'historia_clinica/steps'
      resources :notas_progreso,  :path => "notas_progreso", only: [:new, :create, :index, :destroy, :show, :edit, :update]
    end
  end

  root to: 'pages#home'

 

end
   

app/controllers/paises_controller.rb
class PaisesController < ApplicationController
  before_action :set_pais, only: [:show, :edit, :update, :destroy]

  def index
    @paises = Pais.all
  end

  def show
  end

  def new
    @pais = Pais.new
  end

  def edit
  end

  def create
    @pais = Pais.new(pais_params)

    respond_to do |format|
      if @pais.save
        format.html { redirect_to @pais, notice: 'Pais was successfully created.' }
        format.json { render :show, status: :created, location: @pais }
      else
        format.html { render :new }
        format.json { render json: @pais.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pais.update(pais_params)
        format.html { redirect_to @pais, notice: 'Pais was successfully updated.' }
        format.json { render :show, status: :ok, location: @pais }
      else
        format.html { render :edit }
        format.json { render json: @pais.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pais.destroy
    respond_to do |format|
      format.html { redirect_to paises_url, notice: 'Pais was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_pais
      @pais = Pais.find(params[:id])
    end

    def pais_params
      params.require(:pais).permit(:nombre)
    end
end

app/helpers/paises_helper.rb
module PaisesHelper
end

app/views/paises/_form.html.erb
<%= simple_form_for(@pais) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
	<%= f.input :nombre %></div>

<div class="form-actions">
	<%= f.button :submit %></div>
<% end %>

app/views/paises/edit.html.erb
<h1>Editing Pais</h1>

<%= render 'form' %>

<%= link_to 'Show', @pais %>
|
<%= link_to 'Back', paises_path %>

app/views/paises/index.html.erb
<p id="notice">
  <%= notice %></p>

<h1>Listing Paises</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paises.each do |pais| %>
    <tr>
      <td>
        <%= pais.nombre %></td>
      <td>
        <%= link_to 'Show', pais %></td>
      <td>
        <%= link_to 'Edit', edit_pais_path(pais) %></td>
      <td>
        <%= link_to 'Destroy', pais, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %></tbody>
</table>

<br>

<%= link_to 'New Pais', new_pais_path %>

app/views/paises/new.html.erb
<h1>New Pais</h1>

<%= render 'form' %>

<%= link_to 'Back', paises_path %>

app/views/paises/show.html.erb
<p id="notice">
	<%= notice %></p>

<p> <strong>Nombre:</strong>
	<%= @pais.nombre %></p>

<%= link_to 'Edit', edit_pais_path(@pais) %>
|
<%= link_to 'Back', paises_path %>