config/routes.rb
PetThing::Application.routes.draw do

  
  
  resources :emergencias
  resources :procedimientos_medicos_y_de_enfermeria
  get 'dashboard1/mapa',  to: 'dashboard1#mapa', as: "mapa"

  get 'dashboard1/graficas',  to: 'dashboard1#graficas', as: "graficas"

  get 'informes/index',  to: 'informes#index', as: "info_link"

  get 'informes/mensual_actividades_medicas',    to: 'informes#mensual_actividades_medicas', as: "mensual_actividades_medicas"

  get 'informes/aerocivil',    to: 'informes#aerocivil', as: "aerocivil"

  get 'informes/procedimientos_medicos_enfermeria',    to: 'informes#procedimientos_medicos_enfermeria', as: "procedimientos_medicos_enfermeria"

  get 'informes/pacientes_atendidos_por_empresas',  to: 'informes#pacientes_atendidos_por_empresas', as: "pacientes_atendidos_por_empresas"

  get 'informes/usuarios',  to: 'informes#usuarios', as: "usuarios"

  get 'informes/doctores',  to: 'informes#doctores', as: "doctores"

  get 'informes/historia_usuario',  to: 'informes#historia_usuario', as: "historia_usuario"

  get "reportes", :to => "pages#reportes"

  
  get "get_pacientes/:cedula", to: "pacientes#get_pacientes", as: "get_pacientes"

  resources :paises
  resources :cie10s , :defaults => { :format => :json }

  resources :empresas, :path => "empresas"
  resources :procedimientos, :path => "procedimientos"
  resources :diagnosticos,  :path => "diagnosticos"
  resources :roles, :path => "roles"
  resources :aeropuertos, :path => "aeropuertos"

  resources :ciudades, :path => "ciudades" do
    collection do
      get :autocomplete_ciudad_nombre
    end
  end

  resources :arles, :path => "arl" do
    collection do
      get :autocomplete_arl_nombre
    end
  end

  resources :epses, :path => "eps" do
    collection do
      get :autocomplete_eps_nombre
    end
  end

  resources :users, :path => "usuarios"
  resources :roles, :path => "roles"

  resources :sheets
  resources :material_sheets

  get 'reset_passwords/new'

  get 'pages/home'
  get 'pages/contact'
  get 'pages/help'

  get 'users/historias/:id/:estado', to: "users#historias", as: "users_historias"

  resources :sessions
  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      post :empty_trash
    end
  end

  get       'login',  to:   'sessions#new',       as: :login
  post      'login',  to:   'sessions#create'
  get "logout" => "sessions#destroy", :as => "logout"

   

  resources :pacientes, :path => "pacientes",  only: [:new, :create, :index, :destroy, :show, :edit, :update]  do
    
    resources :historias_clinicas,  :path => "historias_clinicas", only: [:new, :create, :index, :destroy, :show, :edit, :update] do
      resources :historia_fisicas  ,  :path => "historia_fisicas", only: [:new, :create, :index, :destroy, :show, :edit, :update]
      resources :steps,  :path => "steps", only: [:show, :update, :edit], controller: 'historia_clinica/steps'
      resources :notas_progreso,  :path => "notas_progreso", only: [:new, :create, :index, :destroy, :show, :edit, :update]
    end
  end

  root to: 'pages#home'

 

end
   

app/models/emergencia.rb
# == Schema Information
#
# Table name: emergencias
#
#  id                     :integer          not null, primary key
#  user_id                :integer
#  aeropuerto_id          :integer
#  fecha_novedad          :date
#  emergencias            :string
#  notas_de_la_emergencia :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Emergencia < ActiveRecord::Base
  belongs_to :user
  belongs_to :aeropuerto


  def self.search(search)
    where("emergencias like '%#{search}%'  or notas_de_la_emergencia like '%#{search}%' ")
  end

  
end

app/controllers/emergencias_controller.rb
class EmergenciasController < ApplicationController
  before_action :set_emergencia, only: [:show, :edit, :update, :destroy]

  def index
    @emergencias = Emergencia.search(params[:search]).page(params[:page]).per_page(20)
  end

  def show
  end

  def new
    @emergencia = Emergencia.new
  end

  def edit
  end

  def create
    @emergencia = Emergencia.new(emergencia_params)

    respond_to do |format|
      if @emergencia.save
        format.html { redirect_to reportes_path }
        format.json { render :show, status: :created, location: @emergencia }
      else
        format.html { render :new }
        format.json { render json: @emergencia.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @emergencia.update(emergencia_params)
        format.html { redirect_to @emergencia, notice: 'Emergencia was successfully updated.' }
        format.json { render :show, status: :ok, location: @emergencia }
      else
        format.html { render :edit }
        format.json { render json: @emergencia.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @emergencia.destroy
    respond_to do |format|
      format.html { redirect_to emergencias_url, notice: 'Emergencia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_emergencia
      @emergencia = Emergencia.find(params[:id])
    end

    def emergencia_params
      params.require(:emergencia).permit(:user_id, 
        :aeropuerto_id, :fecha_novedad, :emergencias, 
        :notas_de_la_emergencia)
    end
end

app/helpers/emergencias_helper.rb
module EmergenciasHelper
end

app/views/emergencias/_form.html.erb
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
  <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
  <script>
    $(function () {
      $("#fecha_novedad").datepicker();
    });
  </script>

  <style type="text/css" media="screen">.lead { font-size: 33px;margin-bottom:0px; }</style>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
  <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
  <script>
    jQuery.datepicker.regional['eu'] = {
    closeText: 'Egina',
    prevText: '<Aur',
    nextText: 'Hur>',
    currentText: 'Gaur',
    monthNames: ['Enero','Febrero','Marzo','Abril','Mayo','Junio',
    'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'],
    monthNamesShort: ['Ene','Febr','Mar','Abr','May','Jun',
    'Jul','Agos','Sept','Oct','Nov','Dic'],
    dayNames: ['Domingo', 'Lunes','Martes','Miercoles','Jueves','Viernes','Sabado'],
    dayNamesShort: ['Domin', 'Lun','Mart','Mierc','Juev','Viern','Saba'],
    dayNamesMin: ['Do', 'Lu','Ma','Mi','Ju','Vi','Sa'],
    dateFormat: 'yy/mm/dd', firstDay: 1,
    isRTL: false};
    $.datepicker.setDefaults($.datepicker.regional['eu']);
  </script>
</div>

<div class="container-fluid">
  <div id="loginbox" class="mainbox col-md-11 col-sm-11">
    <div class="container-fluid navbar navbar-default" style = "margin-bottom:0px!important">
      <div class="row">
        <%= simple_form_for(@emergencia) do |f| %>
          <% if @emergencia.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@emergencia.errors.count, "error") %> prohibited this pet from being saved:</h2>

              <ul>
              <% @emergencia.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="container-fluid"  style="margin: 10px;">
            <br/><br/>

            <%= link_to "Regresar", reportes_path, :class=>"btn btn-info color_blanco mrg" %>
            <h3 style = "color: #22BDC8;">EMERGENCIAS</h3>
            <div class="row">
              <div class="container-fluid">
                <table class="table">
                  <thead>
                    <tr>
                        <th width="30%">Aeropuerto:</th>
                        <th width="30%">Fecha Novedad:</th>
                        <th width="30%">Emergencias:</th>
                        <th width="10%"></th>
                    </tr> 
                  </thead>
                  <tbody>
                    <tr>
                        <%= f.hidden_field :user_id, :value => current_user.id %>
                      <td>
                        <%= f.collection_select :aeropuerto_id, Aeropuerto.all, :id, :nombre, {prompt: "Campo Obligatorio"}, {class: "form-control"} %>
                      </td>
                      <td>
                        <%= f.text_field :fecha_novedad, class: "form-control", id: "fecha_novedad", placeholder: 'Por Favor ingresa la Fecha de incio' %>
                      </td>
                      <td> 
                        <%= f.text_field :emergencias, class: "form-control" %>
                      </td>

                    </tr>
                  </tbody>
                </table>




                <table class="table">
                  <thead>
                    <tr>
                        <th width="40%">Notas De La Emergencia:</th>
                        <th width="60%"></th>
                    </tr> 
                  </thead>
                  <tbody>
                    <tr>

                      <td>
                        <%= f.text_area :notas_de_la_emergencia, class: "form-control" %>
                      </td>
    
                    </tr>
                  </tbody>
                </table>

                <style>
                  thead tr th {
                    font-size: 15px;
                  }

                </style>


                <div class="well pie_form">
                  <div class="form-actions"  style = "text-align:center!important">
                    <%= f.submit "Guardar", :class => 'btn btn btn-info  custom' %>
                  </div>
                </div>

              </div>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>      

app/views/emergencias/edit.html.erb
<%= render 'form' %>

app/views/emergencias/index.html.erb
<br/>
<br/>

<style type="text/css" media="screen">
th{
  font-size: 12px !important;
}

td{
  font-size: 12px;
}

</style>

<div class="container-fluid">

  <div class="row">

    <div class="col-lg-12">

      <span  class="btn btn-link btn-xs  pull-left pagination pagination">
        <h1 class="title">Emergencias</h1>
      </span>

      <span  class="btn btn-link btn-xs pull-right" style="margin-top:18px;">
        </span>

      <div class="row" >
        <div class="col-lg-12" style="margin-top: -50px;">
          <%= will_paginate @emergencias, renderer: BootstrapPagination::Rails, :previous_label =>'Atras', :next_label => 'Siguiente' %></div>
      </div>


      <table class="table table-bordered table-hover">

        <thead>


          <tr class="x1">
            <th width="3% !important;">Id</th>
            <th width="18% !important;">Fecha y Hora</th>
            <th width="18% !important;">Aeropuerto</th>
            <th width="18% !important;">Usuario</th>
            <th width="18% !important;">Rol</th>
            <th colspan="2" width="18% !important;">Opciones</th>

          </tr>
        </thead>
        <tbody>

          <% @emergencias.each do |emergencia| %>

          <tr class="x">

            <td><%= emergencia.id %></td>
            <td>
              <%= emergencia.created_at.strftime("%d-%m-%Y") %>
              <%= emergencia.created_at.strftime("%X")  %></td>
            <td><%= emergencia.aeropuerto.nombre.capitalize %></td>
            <td><%= emergencia.user.nombres %></td>
            <td><%= emergencia.user.rol.nombre %></td>
            <td>
              <%= link_to emergencia, class: "btn btn-link btn-xs", title: "Ver Usuario" do %> <i class="glyphicon glyphicon-eye-open icono"></i>
              <% end %>
            </td>

            <td>
              <%= link_to edit_emergencia_path(emergencia), class: "btn btn-link btn-xs", title: "Editar Usuario" do %> <i class="glyphicon glyphicon-pencil icono"></i>
              <% end %></td>

          </tr>

          <% end %></table>

      </div>
      <style type="text/css">
    @import url(http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css);
body{margin-top:20px;}
.fa-fw {width: 2em;}
</style>

      <style>

.x td
{
padding: 5px 10px !important;
background-color: #FBFBFB;
color: #828282;
}
.x1 th
{
color: #67B0C7!important;
background: #EFEFEF;
font-size: 15px;      }

</style>

app/views/emergencias/new.html.erb
<%= render 'form' %>

app/views/emergencias/show.html.erb
<div class="container-fluid">
  <div id="loginbox" style = "margin-top: 30px;" class="mainbox col-md-12 col-sm-12">
    <style type="text/css">
      @import url(https://fonts.googleapis.com/css?family=Roboto);
      @import url(https://fonts.googleapis.com/css?family=Montserrat);
      .panel-heading {
          background-image: none;
          background-color: #ECECEC;
          color: #5bc0de;
          font-family: 'Roboto', sans-serif;
      }
      .panel-title{
          font-size: 30px;   
      }
      .pie_form{
          background-image: none;
          background-color: #ECECEC;
          color: white;   
      }
      .line1
      {
          display: inline-block;
          width: 30% !important;
      }
    </style>

    <div class="container-fluid navbar navbar-default">

      <div>

        <br/>
        <br/>

        <div class="row">
          <div class="profile">
            <div class="col-sm-12">
              <div class="container-fluid">
                <div class="row col-md-12  custyle">
                  <h1 style=" font-size:25px; text-align: left;color: #22BDC8; margin-top: 0px;">
                    <span style = "margin-right:10px;color: #22BDC8; "class="glyphicon glyphicon-list-alt"></span>
                    Datos Emergencia
                  </h1>

                  <table class="table table-striped custab table-bordered table-hover">
                    <tr>
                      <th width="20%">Usuario:</th>
                      <td  width="30%">
                        <%= @emergencia.user.nombre_usuario %>
                        </td>
                      <th  width="20%">Aeropuerto:</th>
                      <td  width="30%">
                        <%= @emergencia.aeropuerto.nombre %></td>
                    </tr>
                    <tr>
                      <th>Fecha novedad:</th>
                      <td>
                        <%= @emergencia.fecha_novedad %></td>
                      <th>Emergencias:</th>
                      <td>
                        <%= @emergencia.emergencias.capitalize %></td>
                    </tr>
                    <tr>
                      <th>Notas de la emergencia:</th>
                      <td colspan="3">
                        <%= @emergencia.notas_de_la_emergencia.capitalize %></td>
                    </tr>
                  </table>
                </div>
              </div>
            </div>
            <div class="col-xs-12 text-center">
              <br/>
              <div class="col-xs-12 col-sm-4 emphasis">
                <%= link_to 'Regresar ', emergencias_path, :class =>'btn btn-primary color_blanco principal' %>  
              </div>
              <div class="col-xs-12 col-sm-4 emphasis">
                <%= link_to 'Editar Emergencia',  edit_emergencia_path(@emergencia), :class => 'btn btn-primary  color_blanco principal'  %>
              </div>
              <div class="col-xs-12 col-sm-4 emphasis">
                <%= link_to ' Nueva Emergencia', new_emergencia_path(@emergencia), :class => 'btn btn-primary  color_blanco principal' %>
              </div>
            </div>
          </div>
        </div>
        <br/><br/>
      </div>
    </div>
  </div>
</div>